name: Docker Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: log in to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gsap-landing:latest .

      - name: push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gsap-landing:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            IMAGE=${{ secrets.DOCKERHUB_USERNAME}}/gsap-landing:latest

            docker pull $IMAGE

            docker run -d \
              --name gsap-landing-new \
              --restart unless-stopped \
              $IMAGE

            echo "Waiting for health check to pass..."
            sleep 10

            docker inspect --format='{{.state.Health.Status}}' gsap-landing-new | grep healthy

            docker stop gsap-landing || true
            docker rm gsap-landing || true

            docker rename gsap-landing-new gsap-landing

            docker run --rm \
              --name container:gsap-landing \
              curlimages/curl:http://localhost/health.html